#Versi docker compose
version: "3.7"
services:
  item-app:
    #Mengambil  image item-app dari  GitHub Packages
    image: ghcr.io/wajibhimung/item-app:v1
    #Agar container  restart ketika terhenti
    restart: always
    #port mapping agar dapat diakses dari port 80 di host
    ports:
      - 80:8080 
    #Agar item-app dijalankan setelah item-db   
    depends_on:
      - item-db
    
  item-db:
    #Mengambil  image mongo
    image: mongo:3
    #Agar container  restart ketika terhenti
    restart: always
    #Menuntukan volumes app-db untuk mennyimpan  /data/db 
    volumes:
      - app-db:/data/db  
#membuat volumes app-db  
volumes:
  app-db:

